### ISSUE TITLE
Example server fails to run

### ISSUE THREAD

**Issue by ekynoxe** [nearform/mercurius-federation-info#125]
Running `npm run example` throws the following error:

```
{"type":"Error","message":"Unknown directive "@key".

Unknown directive "@requires".

Unknown directive "@key".

Unknown directive "@extends".

Unknown directive "@external".

Unknown directive "@external".

Unknown directive "@requires".

Cannot extend type "Mutation" because it is not defined.","stack":"Error: Unknown directive "@key".

Unknown directive "@requires".

Unknown directive "@key".

Unknown directive "@extends".

Unknown directive "@external".

Unknown directive "@external".

Unknown directive "@requires".

Cannot extend type "Mutation" because it is not defined.
    at assertValidSDL (/Users/mathieudavy/dev/nearform/mercurius-federation-info/node_modules/graphql/validation/validate.js:135:11)
    at buildASTSchema (/Users/mathieudavy/dev/nearform/mercurius-federation-info/node_modules/graphql/utilities/buildASTSchema.js:44:34)
    at buildSchema (/Users/mathieudavy/dev/nearform/mercurius-federation-info/node_modules/graphql/utilities/buildASTSchema.js:109:10)
    at fp.name (/Users/mathieudavy/dev/nearform/mercurius-federation-info/node_modules/mercurius/index.js:155:14)
    at Plugin.exec (/Users/mathieudavy/dev/nearform/mercurius-federation-info/node_modules/avvio/plugin.js:130:19)
    at Boot.loadPlugin (/Users/mathieudavy/dev/nearform/mercurius-federation-info/node_modules/avvio/plugin.js:272:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
```

Node version: 18.14.2
npm: 9.5.0

**Comment by simoneb** [comment]
@ekynoxe can you look into this? it seems to suggest that the package is quite broken at the moment. Reach out to @codeflyer if you need any help or context
